name: first_project
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter_dotenv: ^5.0.2
  fluttertoast: 8.2.12
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.1.2
  http: ^1.3.0
  flutter_modular: ^6.3.4
  dio: ^5.8.0+1
  flutter_riverpod: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env